Views/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Views.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Views/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CvManagementApp.Models;
using CvManagementApp.Services;
using Microsoft.EntityFrameworkCore;

namespace Views.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ICandidateRepository _candidateRepository;
        private readonly IRepository<Degree> _degreeRepository;

        public IndexModel(ICandidateRepository candidateRepository, IRepository<Degree> degreeRepository)
        {
            _candidateRepository = candidateRepository;
            _degreeRepository = degreeRepository;

            Candidate = new List<Candidate>();
            Degree = new List<Degree>();
        }

        public IList<Candidate> Candidate { get; private set; }
        public IList<Degree> Degree { get; private set; }

        public async Task OnGetAsync()
        {
            Candidate = (await _candidateRepository.GetAllAsyncWithDegrees()).ToList();
            Degree = (await _degreeRepository.GetAllAsync()).ToList();
        }

        public async Task<IActionResult> OnGetDownloadCVAsync(int id)
        {
            var candidate = await _candidateRepository.GetByIdAsync(id);

            if (candidate == null || candidate.CV == null || candidate.CV.Length == 0)
            {
                return NotFound();
            }
            string mimeType = candidate.CVMimeType ?? "application/octet-stream";
            return File(candidate.CV, mimeType, candidate.CVFileName);
        }

        public async Task<IActionResult> OnGetDeleteUnassociatedDegreesAsync()
        {
            var usedDegreeIds = new HashSet<int>((await _candidateRepository.GetAllUsedUniqueDegreesAsync()).Select(d => d.Id));

            foreach (var degree in (await _degreeRepository.GetAllAsync()).Where(d => !usedDegreeIds.Contains(d.Id)))
            {
                await _degreeRepository.DeleteAsync(degree.Id);
            }

            return RedirectToPage();
        }
    }
}

Views/Pages/Index.cshtml
@page
@model Views.Pages.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Candidates</h1>

<p>
    <a asp-page="Candidates/Create">Add New Candidate</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Candidate[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Candidate[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Candidate[0].Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Candidate[0].Mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Candidate[0].Degrees)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Candidate[0].CV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Candidate[0].CreationTime)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Candidate) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @if (item.Degrees != null && item.Degrees.Count > 0)
                {
                    foreach (var degree in item.Degrees)
                    {
                        <div>@degree.Name</div>
                    }
                }
                else
                {
                    @:None
                }
            </td>
            <td>
                @if (item.CV != null && item.CV.Length > 0)
                {
                    <a asp-page="/Index" asp-page-handler="DownloadCV" asp-route-id="@item.Id">@item.CVFileName</a>
                }
                else
                {
                    @:N/A
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationTime)
            </td>
            <td>
                <a asp-page="Candidates/Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="Candidates/Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="Candidates/Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div style="margin-top: 150px;"></div>

<h2>Degrees</h2>

<p>
    <a asp-page="Degrees/Create">Add New Degree</a>
    <span style="margin-left: 50px;">
        <a asp-page="/Index" asp-page-handler="DeleteUnassociatedDegrees">Delete Unassociated Degrees</a>
    </span>
</p>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Degree[0].Name)</th>
            <th>@Html.DisplayNameFor(model => model.Degree[0].CreationTime)</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Degree)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.CreationTime)</td>
                <td>
                    <a asp-page="Degrees/Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="Degrees/Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>